### ISSUE TITLE
Dialog width problem on remove market buttons

### ISSUE THREAD

**Issue by javadghane** [SirLordPouya/AndroidAppUpdater#4]
Hi, thanks for this great library. when dialog create without any market buttons the width of dialog is set to wrap content and changelog text is combined with download link. 

again thanks for this work.

**Comment by SirLordPouya** [comment]
Hi Javad and Thanks for your support.
I have fixed this issue In Version 4.0.0 so I'm closing this issue.
Please reopen this issue if its not fixed yet.
Thanks
