### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by faramarzaf** [SirLordPouya/AndroidAppUpdater#5]
Hi pouya
Does AndroidAppUpdater have callback result for checking that update is available or not??
I mean we can have that option like onUpdateAvailable AND onUpdateNotAvailable, And after that show dialog for different states.
Thanks for your attention :)

**Comment by SirLordPouya** [comment]
Hello Faramarz and thanks for your suggestion.
The responsibility of this library is only to show update dialog to the user.
I have not included these features to avoid complexity, bugs and reduce the size of the library.
Also the response of different web services are definitely different too.
I might make another android library that works with this library and checks for updates and shows the dialog if the update is available.
