### ISSUE TITLE
استفاده در جاوا

### ISSUE THREAD

**Issue by khajenasir** [SirLordPouya/AndroidAppUpdater#6]
چطور میتونم از این کتابخانه در یک پروژه جاوا استفاده کنیم؟چون این کتابخانه کاتلین هست

**Comment by SirLordPouya** [comment]
سلام.
تفاوتی در استفاده جاوا و کاتلین پروژه وجود نداره.
میتونید تمام کلاس های کاتلینی رو در زبان جاوا استفاده کنید.

**Comment by khajenasir** [comment]
متشکرم. البته من یه تغییراتی در نمایش هم دادم. چون معمولا پیشنهاد میشه ابتدا از مارکت ها بروزرسانی انجام بشه و اگه هیچ کدوم رو نصب نداشتن لینک مستقیم کلیک کنید. به همین خاطر جای مارکت ها رو با لینک مستقیم عوض کردم. کتابخانه خیلی خوبی ایجاد کردید متشکرم.
این پایین کدهای تبدیلی جا وا برای استفاده از این کتابخونه رو قرار میدم که اگه کسی خواست استفاده کنه.

`List<UpdaterStoreList> list = new ArrayList<>();

        list.add(new UpdaterStoreList(Store.DIRECT_URL, "دانلود به صورت مستقیم (لینک اول)", R.mipmap.appupdater_ic_cloud , "http://domainname.com/app.apk", BuildConfig.APPLICATION_ID));
        list.add(new UpdaterStoreList(Store.DIRECT_URL, "دانلود به صورت مستقیم (لینک دوم)", R.mipmap.appupdater_ic_cloud , "http://domainname2.com/app.apk", BuildConfig.APPLICATION_ID));

        // stores
        list.add(new UpdaterStoreList(Store.CAFE_BAZAAR, "کافه بازار",R.drawable.appupdater_ic_bazar, "", BuildConfig.APPLICATION_ID));
        list.add(new UpdaterStoreList(Store.MYKET, "مایکت", R.drawable.appupdater_ic_myket, "", BuildConfig.APPLICATION_ID));
        list.add(new UpdaterStoreList(Store.GOOGLE_PLAY, "Play", R.drawable.appupdater_ic_google_play, "", BuildConfig.APPLICATION_ID));

        AppUpdaterDialog.Companion.getInstance("آپدیت جدید رسید!",
                "یک سری امکانات جدید و رمان جدید به برنامه اضافه شده که برای استفاده از اونها باید برنامه رو آپدیت کنی." + "\n" + "برای بروزرسانی روی مارکت مورد نظر بزنید",
                list,
                true,
                font).showNow(getSupportFragmentManager(),"TAG");`
